modLoader="javafml" 
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="bwpmod"
version="1.19.2-0.0.2"
displayName="Better Weapon Progression" 
logoFile="bwpmod.jpg"
authors="Hopsickle"
credits="Thanks to Mackethen for Artwork"
displayURL="https://github.com/andrewhopps/BetterWeaponProgression/issues"
description='''
Adds new upgradeable swords that end up with higher damage than their vanilla counterparts.
'''

[[dependencies.bwpmod]] 
    modId="forge" 
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.bwpmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"